# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.tag.outputs.TAG}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Set image tag
        id: tag
        run: |
          echo '::set-output name=TAG::1.21.4'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v2
        with:
          repository: Thanzex/test-infra
          token: ${{ secrets.TOKEN }} 

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'app/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.build.outputs.tag }}
          repository: Thanzex/test-infra
          branch: main
          targetBranch: main
          message: 'Update Image Version to ${{ steps.build.outputs.tag }}'
          token: ${{ secrets.TOKEN }}
